//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSecurityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileCategory
    {
        public int FileCategoryID { get; set; }
        public int FileID { get; set; }
        public int LookupTableFileCategoryID { get; set; }
    
        public virtual File File { get; set; }
        public virtual LookupTable_FileCategories LookupTable_FileCategories { get; set; }
    }
}
