//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSecurityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PrivateDocView_AllSharedPrivateFiles
    {
        public int FileID { get; set; }
        public int ParentFileID { get; set; }
        public string UserIDOfFileOwner { get; set; }
        public string UserIDOfLastUploaded { get; set; }
        public int FileLookupStatusID { get; set; }
        public int FileShareStatusID { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public int FileSize { get; set; }
        public int CurrentVersionNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string FileStatus { get; set; }
        public string NameOfFileOwner { get; set; }
        public string UserThatLastUpdatedFile { get; set; }
        public string RefID { get; set; }
        public string FullFileName { get; set; }
        public string FileType { get; set; }
    }
}
