//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSecurityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSharedWithUser
    {
        public int FileSharedWithUserID { get; set; }
        public string UserIDOfSharedDocs { get; set; }
        public int FileID { get; set; }
        public System.DateTime DateShared { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual File File { get; set; }
    }
}
