//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSecurityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int FileID { get; set; }
        public int NotificationTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserIDOfNotificationSender { get; set; }
        public string UserIDOfNotificationRecipient { get; set; }
        public bool UserHasAcknowledgement { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual File File { get; set; }
        public virtual LookupTableNotificationType LookupTableNotificationType { get; set; }
    }
}
